name: Java Maven Build & Display Maven Goals Output

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_display:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Display Maven Goals Output
        run: mvn -v
        continue-on-error: true
      - run: mvn clean
        continue-on-error: true
      - run: mvn compile
        continue-on-error: true
      - run: mvn test-compile
        continue-on-error: true
      - run: mvn test
        continue-on-error: true
      - run: mvn package
        continue-on-error: true
      - run: mvn install
        continue-on-error: true
      - run: mvn deploy
        continue-on-error: true
      - run: mvn site
        continue-on-error: true
      - run: mvn site:deploy
        continue-on-error: true
